#Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
#
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
#
#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?


# x = n(3n-1)*(1/2)
# 2x = 3n**2-n
# 0 = 3n**2-n-2x
# n = (-b +-sqrt(b**2-4ac))/2a
# n = (1 +- sqrt(1-4(-6x))/6
#if this: (sqrt(1+24x)+1)/6 OR (-sqrt(1+24x)+1)/6 is an integer, then x is a pentagonal number and the formula gives its index.


class Integer
	def pentagon?
		((((1+(24 * self))**0.5).abs + 1) / 6) % 1 == 0
	end
	
	def pentagonize
		(self*((3*self)-1))/2
	end
end

answer=999999999

(1..5000).each do |j|
	((j+1)..(5000)).each do |k|
		pj,pk = j.pentagonize, k.pentagonize
		d = pk - pj
		break if d > answer
		next unless d.pentagon?
		answer = d if (pj+pk).pentagon?
	end
end

puts answer