#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
#Hexagonal 	  	Hn=n(2n-1) 	  	1, 6, 15, 28, 45, ...
#
#It can be verified that T285 = P165 = H143 = 40755.
#
#Find the next triangle number that is also pentagonal and hexagonal.

#inverses for each formula:
#triangle: (Sqrt(1+8n)-1)/2
#pentagon: (sqrt(1+24n)+1)/6
#hexagon: (sqrt(1+8n)+1)/4 
start = Time.now
class Integer
	def triangle?
		((((1+(8*self))**0.5)-1)/2) % 1 == 0
	end
	def pentagon?
		((((1+(24 * self))**0.5)+1)/6) % 1 == 0
	end
#	def hexagon?
#		((((1+(8*self))**0.5)+1)/4) % 1 == 0
#	end
end

n = 144

loop do
	hex = n*((2*n)-1)
	if hex.pentagon? and hex.triangle?
		puts hex
		puts "#{((Time.now - start)*1000).to_i} ms elapsed."
		exit
	end
	n += 1
end

